spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voting
    username: voting
    password: voting01
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
